title: Your website title
url: "https://monsoonmalabar.com/kmstores"
email: ''
markdown: kramdown
mobile: ''
country: ''
location: ''
sass:
  sass_dir: _sass
  style: compressed
collections:
  products:
    output: true
defaults:
  - scope:
      type: posts
    values:
      layout: product
  - scope:
      type: products
    values:
      layout: post
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
encoding: UTF-8
permalink: /products/:title/
paginate: 4
paginate_path: 'page/:num/'
favicon: 
paypal: ''
analytics: ''
adsense: ''